import json
from typing import List, Literal, Optional

from pydantic import BaseModel, Field


# ── 动画专用灯光预设 ──────────────────────────────────────

ANIM_LIGHTING_PRESETS = {
    "studio": {
        "bg_color": (0.15, 0.15, 0.18),
        "lights": [
            {"type": "AREA", "location": (2, -2, 2.5), "energy": 800, "color": (1.0, 0.95, 0.9), "size": 2.0},
            {"type": "AREA", "location": (-1.5, -1.5, 1.8), "energy": 300, "color": (0.9, 0.95, 1.0), "size": 1.5},
            {"type": "AREA", "location": (0, 2, 2.5), "energy": 500, "color": (1.0, 1.0, 1.0), "size": 1.0},
        ],
    },
    "dramatic": {
        "bg_color": (0.02, 0.02, 0.03),
        "lights": [
            {"type": "AREA", "location": (3, -1, 2), "energy": 1200, "color": (1.0, 0.9, 0.7), "size": 1.5},
            {"type": "AREA", "location": (-2, -2, 1), "energy": 80, "color": (0.6, 0.7, 1.0), "size": 1.0},
        ],
    },
    "soft": {
        "bg_color": (0.6, 0.6, 0.65),
        "lights": [
            {"type": "AREA", "location": (0, -3, 2.5), "energy": 600, "color": (1.0, 1.0, 1.0), "size": 4.0},
        ],
    },
    "neon": {
        "bg_color": (0.02, 0.02, 0.05),
        "lights": [
            {"type": "AREA", "location": (3, 0, 2), "energy": 1000, "color": (1.0, 0.0, 0.8), "size": 1.5},
            {"type": "AREA", "location": (-3, 0, 2), "energy": 1000, "color": (0.0, 0.9, 1.0), "size": 1.5},
            {"type": "AREA", "location": (0, -2, 2.5), "energy": 300, "color": (1.0, 1.0, 1.0), "size": 2.0},
        ],
    },
}

# ── 动画专用相机预设 ──────────────────────────────────────

ANIM_CAMERA_PRESETS = {
    "front": {
        "location": (0, -3, 1.5),
        "rotation": (1.1, 0, 0),
        "track_character": False,
    },
    "side": {
        "location": (3, 0, 1.5),
        "rotation": (1.1, 0, 1.5708),
        "track_character": False,
    },
    "three_quarter": {
        "location": (2.1, -2.1, 1.5),
        "rotation": (1.1, 0, 0.7854),
        "track_character": False,
    },
    "follow": {
        "location": (0, -3, 1.5),
        "rotation": (1.1, 0, 0),
        "track_character": True,
    },
    "orbit": {
        "location": (0, -3, 1.5),
        "rotation": (1.1, 0, 0),
        "track_character": False,
        "orbit": True,
    },
}


class AnimationParams(BaseModel):
    """动画渲染参数"""
    preset_name: str = Field(..., description="输出文件名前缀，如 'hero_walk'")
    character: str = Field(..., description="角色 FBX 文件名，如 'hero.fbx'")
    motions: List[str] = Field(..., description="动画 FBX 文件名列表，如 ['walk.fbx', 'run.fbx']")
    output_format: Literal["frames", "video", "both"] = "frames"
    resolution: int = 1024
    samples: int = Field(256, ge=32, le=2048)
    fps: int = 24
    lighting_preset: Literal["studio", "dramatic", "soft", "neon"] = "studio"
    camera_preset: Literal["front", "side", "three_quarter", "follow", "orbit"] = "three_quarter"
    transparent_bg: bool = False
    character_scale: float = Field(1.0, description="角色缩放因子")


def generate_animation_script(
    params: AnimationParams,
    output_dir: str = "D:/BlenderAgent/outputs",
    characters_dir: str = "D:/BlenderAgent/animations/characters",
    motions_dir: str = "D:/BlenderAgent/animations/motions",
) -> str:
    """生成 Blender Python 脚本 - 导入 Mixamo FBX 并渲染动画

    工作流：
    1. 导入角色 FBX（Mixamo Auto-Rigged）
    2. 逐个导入动画 FBX，提取 Action 并应用到角色骨骼
    3. 为每个动画渲染帧序列和/或视频
    """
    lighting = ANIM_LIGHTING_PRESETS[params.lighting_preset]
    lights_json = json.dumps(lighting["lights"])
    bg_color = lighting["bg_color"]
    camera_cfg = ANIM_CAMERA_PRESETS[params.camera_preset]
    camera_json = json.dumps(camera_cfg)

    script_lines = [
        "import bpy",
        "import json",
        "import math",
        "import os",
        "",
        "# ── 清理场景 ────────────────────────────────────",
        "bpy.ops.object.select_all(action='SELECT')",
        "bpy.ops.object.delete(use_global=False)",
        "",
        "# 清除残留的 orphan data",
        "for block in bpy.data.meshes:",
        "    if block.users == 0: bpy.data.meshes.remove(block)",
        "for block in bpy.data.armatures:",
        "    if block.users == 0: bpy.data.armatures.remove(block)",
        "for block in bpy.data.actions:",
        "    if block.users == 0: bpy.data.actions.remove(block)",
        "",
        "# ── 导入角色 ────────────────────────────────────",
        f'char_path = r"{characters_dir}/{params.character}"',
        "if not os.path.isfile(char_path):",
        '    raise FileNotFoundError("角色文件不存在: " + char_path)',
        "",
        "bpy.ops.import_scene.fbx(",
        "    filepath=char_path,",
        "    use_anim=True,",
        "    automatic_bone_orientation=True,",
        "    ignore_leaf_bones=True,",
        f"    global_scale={params.character_scale},",
        ")",
        "",
        "# 查找角色的 Armature",
        "char_armature = None",
        "char_meshes = []",
        "for obj in bpy.context.selected_objects:",
        "    if obj.type == 'ARMATURE':",
        "        char_armature = obj",
        "    elif obj.type == 'MESH':",
        "        char_meshes.append(obj)",
        "",
        "if char_armature is None:",
        '    raise RuntimeError("角色 FBX 中未找到 Armature")',
        f'print("角色已导入: " + char_armature.name)',
        "",
        "# ── 地面（阴影捕捉）──────────────────────────────",
        "bpy.ops.mesh.primitive_plane_add(size=10, location=(0, 0, 0))",
        "ground = bpy.context.object",
        'ground.name = "Ground"',
        "ground_mat = bpy.data.materials.new(name='ShadowCatcher')",
        "ground_mat.use_nodes = True",
        "ground_mat.node_tree.nodes['Principled BSDF'].inputs['Alpha'].default_value = 0.0",
        "try:",
        "    ground.is_shadow_catcher = True",
        "except (AttributeError, Exception):",
        "    try:",
        "        ground.cycles.is_shadow_catcher = True",
        "    except (AttributeError, Exception):",
        "        pass",
        "ground.data.materials.append(ground_mat)",
        "",
        "# ── 灯光 ──────────────────────────────────────",
        f"bg_color = {bg_color}",
        "lights_config = " + lights_json,
        "for lc in lights_config:",
        "    bpy.ops.object.light_add(type=lc['type'], location=lc['location'])",
        "    lt = bpy.context.object",
        "    lt.data.energy = lc['energy']",
        "    lt.data.color = lc['color']",
        "    if hasattr(lt.data, 'size'):",
        "        lt.data.size = lc.get('size', 1.0)",
        "",
        "# 世界背景",
        "world = bpy.data.worlds.new(name='World')",
        "bpy.context.scene.world = world",
        "world.use_nodes = True",
        "bg_node = world.node_tree.nodes['Background']",
        "bg_node.inputs[0].default_value = bg_color + (1,)",
        "bg_node.inputs[1].default_value = 1",
        "",
        "# ── 相机 ──────────────────────────────────────────",
        'cam_data = bpy.data.cameras.new(name="AnimCamera")',
        'camera = bpy.data.objects.new("AnimCamera", cam_data)',
        "bpy.context.scene.collection.objects.link(camera)",
        "bpy.context.scene.camera = camera",
        "camera_cfg = " + camera_json,
        "camera.location = camera_cfg['location']",
        "camera.rotation_euler = camera_cfg['rotation']",
        "",
        "# ── 渲染设置 ──────────────────────────────────────",
        "scene = bpy.context.scene",
        "scene.render.engine = 'CYCLES'",
        "scene.cycles.device = 'GPU'",
        f"scene.render.resolution_x = {params.resolution}",
        f"scene.render.resolution_y = {params.resolution}",
        "scene.render.resolution_percentage = 100",
        f"scene.render.fps = {params.fps}",
        f"scene.cycles.samples = {params.samples}",
        f"scene.render.film_transparent = {str(params.transparent_bg)}",
        "",
        "# 降噪 + 色调映射",
        "scene.cycles.use_denoising = True",
        "try:",
        "    scene.cycles.denoiser = 'OPTIX'",
        "except Exception:",
        "    pass",
        "try:",
        "    scene.view_settings.view_transform = 'AgX'",
        "except Exception:",
        "    pass",
        "",
        "# 光路弹射",
        "scene.cycles.max_bounces = 12",
        "scene.cycles.diffuse_bounces = 8",
        "scene.cycles.glossy_bounces = 8",
        "",
        "# GPU",
        "try:",
        "    prefs = bpy.context.preferences.addons['cycles'].preferences",
        "    prefs.get_devices()",
        "    prefs.compute_device_type = 'OPTIX'",
        "    for d in prefs.devices:",
        "        d.use = d.type != 'CPU'",
        "    bpy.ops.wm.save_userpref()",
        "except Exception:",
        "    pass",
        "",
        "# ── 逐个处理动画 ──────────────────────────────────",
        "output_paths = []",
        "motions = " + json.dumps(params.motions),
        "output_format = " + json.dumps(params.output_format),
        "",
        "for motion_idx, motion_file in enumerate(motions):",
        f'    motion_path = r"{motions_dir}/" + motion_file',
        "    if not os.path.isfile(motion_path):",
        '        print("WARN: 动画文件不存在，跳过: " + motion_path)',
        "        continue",
        "",
        "    # 导入动画 FBX",
        "    bpy.ops.import_scene.fbx(",
        "        filepath=motion_path,",
        "        use_anim=True,",
        "        automatic_bone_orientation=True,",
        "        ignore_leaf_bones=True,",
        "    )",
        "",
        "    # 查找导入的动画 Armature",
        "    motion_armature = None",
        "    motion_action = None",
        "    imported_objects = list(bpy.context.selected_objects)",
        "    for obj in imported_objects:",
        "        if obj.type == 'ARMATURE':",
        "            motion_armature = obj",
        "            if obj.animation_data and obj.animation_data.action:",
        "                motion_action = obj.animation_data.action",
        "            break",
        "",
        "    if motion_action is None:",
        '        print("WARN: 未找到动画 Action，跳过: " + motion_file)',
        "        # 清理导入的对象",
        "        for obj in imported_objects:",
        "            bpy.data.objects.remove(obj, do_unlink=True)",
        "        continue",
        "",
        f'    motion_name = os.path.splitext(motion_file)[0]',
        '    print(f"处理动画: {motion_name} (帧 {int(motion_action.frame_range[0])}-{int(motion_action.frame_range[1])})")',
        "",
        "    # 将 Action 复制到角色骨骼",
        "    new_action = motion_action.copy()",
        "    new_action.name = f'{char_armature.name}_{motion_name}'",
        "    if not char_armature.animation_data:",
        "        char_armature.animation_data_create()",
        "    char_armature.animation_data.action = new_action",
        "",
        "    # 设置帧范围",
        "    frame_start = int(motion_action.frame_range[0])",
        "    frame_end = int(motion_action.frame_range[1])",
        "    scene.frame_start = frame_start",
        "    scene.frame_end = frame_end",
        "",
        "    # 设置相机（follow/orbit 模式需要在每帧更新）",
        "    track_char = camera_cfg.get('track_character', False)",
        "    orbit_mode = camera_cfg.get('orbit', False)",
        "    base_cam_loc = list(camera_cfg['location'])",
        "    base_cam_rot = list(camera_cfg['rotation'])",
        "",
        "    if orbit_mode:",
        "        # 轨道模式：动画期间相机绕角色旋转",
        "        total_frames = frame_end - frame_start",
        "        if total_frames > 0:",
        "            cam_obj = camera",
        "            hips_name = None",
        "            for bone in char_armature.data.bones:",
        "                if 'Hips' in bone.name:",
        "                    hips_name = bone.name",
        "                    break",
        "",
        "    # 渲染帧序列（PNG）",
        "    if output_format in ('frames', 'both'):",
        f'        frames_dir = r"{output_dir}/{params.preset_name}_" + motion_name',
        '        os.makedirs(frames_dir, exist_ok=True)',
        '        scene.render.image_settings.file_format = "PNG"',
        '        scene.render.image_settings.color_mode = "RGBA"',
        "",
        "        if orbit_mode:",
        "            # 轨道模式：逐帧渲染并旋转相机",
        "            total = frame_end - frame_start",
        "            for fi, frame in enumerate(range(frame_start, frame_end + 1)):",
        "                scene.frame_set(frame)",
        "                angle = (fi / max(total, 1)) * 2 * math.pi",
        "                radius = 3.0",
        "                camera.location = (radius * math.sin(angle), -radius * math.cos(angle), 1.5)",
        "                camera.rotation_euler = (1.1, 0, angle)",
        "                filepath = os.path.join(frames_dir, f'{{:04d}}.png'.format(frame))",
        "                scene.render.filepath = filepath",
        "                bpy.ops.render.render(write_still=True)",
        "        elif track_char:",
        "            # 跟随模式：逐帧渲染，相机跟随角色根骨骼",
        "            hips_bone = None",
        "            for bone in char_armature.pose.bones:",
        "                if 'Hips' in bone.name:",
        "                    hips_bone = bone",
        "                    break",
        "            for frame in range(frame_start, frame_end + 1):",
        "                scene.frame_set(frame)",
        "                if hips_bone:",
        "                    hips_pos = char_armature.matrix_world @ hips_bone.head",
        "                    camera.location = (hips_pos.x, hips_pos.y - 3, 1.5)",
        "                filepath = os.path.join(frames_dir, f'{{:04d}}.png'.format(frame))",
        "                scene.render.filepath = filepath",
        "                bpy.ops.render.render(write_still=True)",
        "        else:",
        "            # 固定机位：批量渲染",
        "            scene.render.filepath = os.path.join(frames_dir, '')",
        "            bpy.ops.render.render(animation=True)",
        "",
        '        output_paths.append(frames_dir)',
        f'        print(f"帧序列已渲染: {{frames_dir}}")',
        "",
        "    # 渲染视频（MP4）",
        "    if output_format in ('video', 'both'):",
        f'        video_path = r"{output_dir}/{params.preset_name}_" + motion_name + ".mp4"',
        '        scene.render.image_settings.file_format = "FFMPEG"',
        '        scene.render.ffmpeg.format = "MPEG4"',
        '        scene.render.ffmpeg.codec = "H264"',
        "        scene.render.ffmpeg.video_bitrate = 6000",
        "        scene.render.ffmpeg.gopsize = 12",
        "        scene.render.filepath = video_path",
        "",
        "        # 轨道/跟随模式下逐帧写入视频比较复杂，先用固定机位",
        "        bpy.ops.render.render(animation=True)",
        '        output_paths.append(video_path)',
        f'        print(f"视频已渲染: {{video_path}}")',
        "",
        "    # 清理动画临时对象（保留 Action 副本在角色上）",
        "    for obj in imported_objects:",
        "        if obj != char_armature and obj not in char_meshes:",
        "            bpy.data.objects.remove(obj, do_unlink=True)",
        "    # 清理原始 Action（保留复制的）",
        "    if motion_action.users == 0:",
        "        bpy.data.actions.remove(motion_action)",
        "",
        "# 清除当前 Action",
        "if char_armature.animation_data:",
        "    char_armature.animation_data.action = None",
        "",
        'print("ANIMATION_RENDER_COMPLETE")',
        "print(json.dumps(output_paths))",
    ]
    return "\n".join(script_lines)
