#!/usr/bin/env python3
"""
Blender 场景布局引擎
根据场景JSON定义生成Blender Python脚本
"""

import argparse
import json
import sys
from pathlib import Path


def generate_blender_script(scene_data: dict, assets_data: dict) -> str:
    """根据场景定义生成Blender Python脚本"""
    
    lines = [
        '"""',
        f'Auto-generated by kais-blender-layout',
        f'Scene: {scene_data.get("scene", {}).get("name", "unnamed")}',
        '"""',
        '',
        'import bpy',
        'import os',
        '',
        '# 清空场景',
        'bpy.ops.wm.read_factory_settings(use_empty=True)',
        '',
        'def clear_scene():',
        '    for obj in bpy.data.objects:',
        '        bpy.data.objects.remove(obj, do_unlink=True)',
        '    for mat in bpy.data.materials:',
        '        if mat.users == 0:',
        '            bpy.data.materials.remove(mat)',
        '',
        'clear_scene()',
        '',
        '# 设置渲染参数',
        'scene = bpy.context.scene',
        f'scene.render.resolution_x = {scene_data.get("render", {}).get("width", 1920)}',
        f'scene.render.resolution_y = {scene_data.get("render", {}).get("height", 1080)}',
        f'scene.render.fps = {scene_data.get("render", {}).get("fps", 24)}',
        f'scene.frame_start = {scene_data.get("render", {}).get("frame_start", 0)}',
        f'scene.frame_end = {scene_data.get("render", {}).get("frame_end", 250)}',
        '',
    ]
    
    # 环境导入
    scene_info = scene_data.get("scene", {})
    if scene_info.get("environment"):
        env_name = scene_info["environment"]
        env_file = find_asset(assets_data, "environments", env_name)
        if env_file:
            lines.extend([
                f'# 导入环境: {env_name}',
                f'env_path = r"{env_file}"',
                'if os.path.exists(env_path):',
                '    bpy.ops.import_scene.fbx(filepath=env_path)',
                '',
            ])
    
    # 灯光设置
    lighting = scene_info.get("lighting", {})
    if lighting:
        lines.extend([
            '# 灯光设置',
            '',
        ])
        
        if lighting.get("type") == "dramatic":
            lines.extend([
                '# 主光源',
                'key_data = bpy.data.lights.new("KeyLight", "SPOT")',
                'key_obj = bpy.data.objects.new("KeyLight", key_data)',
                'bpy.context.collection.objects.link(key_obj)',
            ])
            key_pos = lighting.get("key_light", {}).get("position", [5, 8, 3])
            lines.extend([
                f'key_obj.location = {key_pos}',
                'key_data.energy = 1000',
                'key_data.spot_size = 1.2',
                '',
                '# 补光',
                'fill_data = bpy.data.lights.new("FillLight", "AREA")',
                'fill_obj = bpy.data.objects.new("FillLight", fill_data)',
                'bpy.context.collection.objects.link(fill_obj)',
                'fill_obj.location = [-3, -2, 4]',
                f'fill_data.energy = {lighting.get("fill_light", {}).get("intensity", 0.3) * 500}',
                '',
                '# 背光/轮廓光',
                'back_data = bpy.data.lights.new("BackLight", "SPOT")',
                'back_obj = bpy.data.objects.new("BackLight", back_data)',
                'bpy.context.collection.objects.link(back_obj)',
                'back_obj.location = [0, 3, 5]',
                'back_data.energy = 500',
                '',
            ])
        elif lighting.get("type") == "studio":
            lines.extend([
                'bpy.ops.object.light_add(type="AREA", location=(0, -3, 5))',
                'bpy.context.active_object.data.energy = 800',
                'bpy.ops.object.light_add(type="AREA", location=(-3, -3, 3))',
                'bpy.context.active_object.data.energy = 300',
                'bpy.ops.object.light_add(type="AREA", location=(3, -3, 3))',
                'bpy.context.active_object.data.energy = 300',
                '',
            ])
    
    # 相机设置
    camera = scene_info.get("camera", {})
    if camera:
        lines.extend([
            '# 相机设置',
            'bpy.ops.object.camera_add()',
            'cam = bpy.context.active_object',
            'cam.name = "MainCamera"',
            'scene.camera = cam',
            f'cam.location = {camera.get("position", [0, -5, 2])}',
            '',
            'import math',
        ])
        look_at = camera.get("look_at")
        if look_at:
            lines.append(f'cam.rotation_euler = (1.1, 0, 0)  # 面向"{look_at}"')
        lines.append('')
    
    # 角色导入与摆放
    characters = scene_data.get("characters", [])
    if characters:
        lines.append('# 角色导入与摆放')
        lines.append('')
        
        for i, char in enumerate(characters):
            model_name = char["model"]
            model_file = find_asset(assets_data, "models", model_name)
            pos = char.get("position", [0, 0, 0])
            rot = char.get("rotation", [0, 0, 0])
            
            lines.append(f'# 角色 {i+1}: {model_name}')
            if model_file:
                lines.extend([
                    f'char_path_{i} = r"{model_file}"',
                    f'if os.path.exists(char_path_{i}):',
                    f'    bpy.ops.import_scene.fbx(filepath=char_path_{i})',
                    f'    char_{i} = bpy.context.active_object',
                    f'    char_{i}.name = "{model_name}"',
                    f'    char_{i}.location = {pos}',
                    f'    char_{i}.rotation_euler = [r * 3.14159 / 180 for r in {rot}]',
                    '',
                ])
            else:
                lines.append(f'# ⚠️ 模型未找到: {model_name}')
                lines.append('')
    
    # 道具导入
    props = scene_data.get("props", [])
    if props:
        lines.append('# 道具导入')
        lines.append('')
        for i, prop in enumerate(props):
            model_name = prop.get("model", f"prop_{i}")
            model_file = find_asset(assets_data, "models", model_name)
            pos = prop.get("position", [0, 0, 0])
            if model_file:
                lines.extend([
                    f'prop_path_{i} = r"{model_file}"',
                    f'if os.path.exists(prop_path_{i}):',
                    f'    bpy.ops.import_scene.fbx(filepath=prop_path_{i})',
                    f'    prop_{i} = bpy.context.active_object',
                    f'    prop_{i}.name = "{model_name}"',
                    f'    prop_{i}.location = {pos}',
                    '',
                ])
    
    # 动画绑定
    timeline = scene_data.get("timeline", [])
    if timeline:
        lines.extend([
            '# 动画时间轴编排',
            '',
            'def bind_animation(armature_name, anim_file, start_frame=0):',
            '    """将Mixamo动画绑定到角色骨架"""',
            '    if not os.path.exists(anim_file):',
            '        print(f"动画文件不存在: {anim_file}")',
            '        return',
            '    armature = bpy.data.objects.get(armature_name)',
            '    if not armature:',
            '        print(f"骨架不存在: {armature_name}")',
            '        return',
            '    # 导入动画（保留rest pose）',
            '    prev_active = bpy.context.view_layer.objects.active',
            '    bpy.context.view_layer.objects.active = armature',
            '    bpy.ops.import_scene.fbx(filepath=anim_file)',
            '    # 获取导入的action',
            '    actions = list(bpy.data.actions)',
            '    if actions:',
            '        action = actions[-1]',
            '        # NLA轨道绑定',
            '        if not armature.animation_data:',
            '            armature.animation_data_create()',
            '        track = armature.animation_data.nla_tracks.new()',
            '        strip = track.strips.new(action.name, start_frame, action)',
            '        strip.blend_type = "REPLACE"',
            '    bpy.context.view_layer.objects.active = prev_active',
            '',
        ])
        
        # 为每个角色生成动画绑定代码
        bound_chars = set()
        for event in timeline:
            action_str = event.get("action", "")
            if "." in action_str:
                char_name, anim_name = action_str.split(".", 1)
                if char_name not in bound_chars:
                    anim_file = find_asset(assets_data, "animations", anim_name)
                    if anim_file:
                        frame = event.get("frame", 0)
                        lines.append(f'bind_animation("{char_name}", r"{anim_file}", start_frame={frame})')
                    bound_chars.add(char_name)
    
    lines.extend([
        '',
        'print("✅ 场景搭建完成")',
    ])
    
    return "\n".join(lines)


def find_asset(assets_data: dict, category: str, name: str) -> str:
    """在资产索引中查找文件路径"""
    items = assets_data.get(category, [])
    for item in items:
        if item.get("name", "").lower() == name.lower():
            return item.get("file", "")
    return ""


def main():
    parser = argparse.ArgumentParser(description="Blender场景布局引擎")
    parser.add_argument("command", choices=["generate", "extract"], help="命令")
    parser.add_argument("--scene", help="场景定义JSON文件")
    parser.add_argument("--assets", required=True, help="资产索引JSON文件")
    parser.add_argument("--output", default="scene_setup.py", help="输出脚本文件")
    parser.add_argument("--storyboard", help="分镜脚本文件（extract模式）")
    
    args = parser.parse_args()
    
    # 加载资产索引
    assets_data = {}
    if args.assets and os.path.exists(args.assets):
        with open(args.assets, "r", encoding="utf-8") as f:
            assets_data = json.load(f)
    
    if args.command == "generate":
        if not args.scene:
            print("❌ 需要 --scene 参数", file=sys.stderr)
            sys.exit(1)
        
        with open(args.scene, "r", encoding="utf-8") as f:
            scene_data = json.load(f)
        
        script = generate_blender_script(scene_data, assets_data)
        
        output_path = Path(args.output)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(script, encoding="utf-8")
        
        print(f"✅ 脚本生成完成: {args.output}")
        print(f"   场景: {scene_data.get('scene', {}).get('name', 'unnamed')}")
        print(f"   角色: {len(scene_data.get('characters', []))}")
        print(f"   道具: {len(scene_data.get('props', []))}")
        print(f"   时间线事件: {len(scene_data.get('timeline', []))}")
    
    elif args.command == "extract":
        print("⚠️ extract功能开发中，暂不支持从分镜脚本自动提取")
        print("请手动编写scene.json或使用自然语言→JSON转换")


if __name__ == "__main__":
    main()
