#!/usr/bin/env python3
"""
Autoresearch Project Initializer
Creates autoresearch/ directory and project.md template based on project type.
"""

import argparse
import os
import sys
from pathlib import Path

TEMPLATES = {
    "web": {
        "goal": "Optimize web application performance",
        "metric_name": "Lighthouse Performance Score",
        "metric_direction": "higher",
        "command": "npx lighthouse http://localhost:3000 --output=json --chrome-flags=\"--headless\" --quiet",
        "parse": "Look for categories.performance.score in JSON output (0-1 scale)",
        "editable": "src/components/**, src/utils/**, src/app/**, next.config.*, vite.config.*, webpack.config.*, tailwind.config.*",
        "readonly": "public/**, tests/**, package.json, node_modules/**",
        "time_budget": 120,
        "guard": "npm run build 2>&1 | tail -5",
    },
    "api": {
        "goal": "Optimize API response time and throughput",
        "metric_name": "P99 Latency (ms)",
        "metric_direction": "lower",
        "command": "python scripts/benchmark.py",
        "parse": "Look for 'p99:' in output, extract number in ms",
        "editable": "src/routes/**, src/middleware/**, src/models/**, src/utils/**, config/**",
        "readonly": "tests/**, migrations/**, package.json",
        "time_budget": 60,
        "guard": "python -m pytest tests/ -q 2>&1 | tail -3",
    },
    "ml": {
        "goal": "Improve model performance on validation set",
        "metric_name": "Validation Loss",
        "metric_direction": "lower",
        "command": "python train.py --epochs 1 --fast",
        "parse": "Look for 'val_loss:' in output, extract float",
        "editable": "model.py, train.py, config.py, src/model/**, src/training/**",
        "readonly": "data/**, prepare.py, tests/**",
        "time_budget": 300,
        "guard": "python -c \"import model; print('import ok')\" 2>&1",
    },
    "cli": {
        "goal": "Optimize CLI tool execution speed",
        "metric_name": "Mean Execution Time (ms)",
        "metric_direction": "lower",
        "command": "hyperfine 'cargo run --release -- input.txt' --runs 10 --output=pipe",
        "parse": "Look for 'Mean' line, extract time in ms",
        "editable": "src/**/*.rs, src/**/*.go, src/**/*.py, Cargo.toml, go.mod",
        "readonly": "tests/**, benches/**",
        "time_budget": 60,
        "guard": "cargo test --quiet 2>&1 | tail -3",
    },
    "prompt": {
        "goal": "Optimize prompt engineering for better eval scores",
        "metric_name": "Eval Score",
        "metric_direction": "higher",
        "command": "python eval.py --prompt-file prompts/current.txt",
        "parse": "Look for 'score:' in output, extract float (0-100)",
        "editable": "prompts/**, src/pipeline.py, src/eval.py",
        "readonly": "data/**, tests/**, requirements.txt",
        "time_budget": 120,
        "guard": "python -c \"import eval; print('ok')\" 2>&1",
    },
    "generic": {
        "goal": "Optimize [DESCRIBE YOUR GOAL HERE]",
        "metric_name": "[METRIC NAME]",
        "metric_direction": "lower",  # or "higher"
        "command": "[COMMAND TO RUN EXPERIMENT]",
        "parse": "[HOW TO EXTRACT METRIC FROM OUTPUT]",
        "editable": "[FILES AGENT CAN MODIFY]",
        "readonly": "[FILES AGENT MUST NOT MODIFY]",
        "time_budget": 60,
        "guard": "[COMMAND TO VERIFY CODE STILL WORKS]",
    },
}

PROJECT_MD_TEMPLATE = """# Autoresearch Project

> Auto-generated by autoresearch init script
> Edit this file to configure your autonomous research loop

## Goal
{goal}

## Metric
- Primary: {metric_name} ({direction} is better)
- Command: `{command}`
- Parse: {parse}

## Scope
- Editable: {editable}
- Read-only: {readonly}
- No new dependencies: true

## Constraints
- Time budget: {time_budget} seconds per experiment
- Kill experiment if it exceeds 2x the time budget
- Simplicity: prefer removing code over adding it for equal gains

## Guard Rails
- Must pass: `{guard}`
- Failing guard = automatic discard (even if metric improved)

## Baseline
- Run the experiment command as-is first to establish baseline
- Record baseline metric in results.tsv

## Ideas (optional starting points)
- [Add initial experiment ideas here, or leave blank for agent to explore]

---

## Experiment Loop

LOOP FOREVER (until human stops you):

1. Read the current git state (branch, commit)
2. Look at results.tsv for what's been tried
3. Form a hypothesis:
   - What worked before? (keep patterns)
   - What almost worked? (combine partial wins)
   - What hasn't been tried? (code understanding + domain knowledge)
4. Implement by editing files in the Editable scope
5. git commit with descriptive message
6. Run: {command}
7. Parse the metric from output
8. Record in results.tsv:
   - If improved → status=keep, advance branch
   - If worse/equal → status=discard, git reset --hard
   - If crash → status=crash, fix if trivial, skip if not
9. Go to step 1

## Rules

- NEVER STOP. Keep going until human interrupts.
- NEVER ask "should I continue?"
- NEVER modify files outside Editable scope.
- NEVER install new dependencies.
- If crash: read error, fix if trivial, skip if fundamental.
- If stuck: re-read code, combine near-misses, try radical changes.
- Simplicity wins: removing code for equal perf > adding code for tiny gains.

## Productivity Estimate

- Each experiment: ~{time_budget}s
- Per hour: ~{per_hour} experiments
- Overnight (8h): ~{overnight} experiments
"""

def detect_project_type(path: str) -> str:
    """Auto-detect project type from files in directory."""
    p = Path(path)
    files = {f.name for f in p.iterdir() if f.is_file()}
    dirs = {d.name for d in p.iterdir() if d.is_dir()}

    if "next.config.js" in files or "next.config.mjs" in files or "next.config.ts" in files:
        return "web"
    if "package.json" in files:
        with open(p / "package.json") as f:
            content = f.read().lower()
            if "next" in content or "react" in content or "vue" in content:
                return "web"
            if "express" in content or "fastify" in content or "koa" in content:
                return "api"
            if "vite" in content and "lighthouse" in content:
                return "web"
    if "Cargo.toml" in files:
        return "cli"
    if "go.mod" in files:
        return "cli"
    if "train.py" in files or "model.py" in files:
        return "ml"
    if "pyproject.toml" in files:
        with open(p / "pyproject.toml") as f:
            content = f.read().lower()
            if "torch" in content or "tensorflow" in content:
                return "ml"
            if "fastapi" in content or "flask" in content:
                return "api"
    if "prompts" in dirs:
        return "prompt"
    return "generic"


def analyze_project(project_path: Path, project_type: str) -> str:
    """Analyze project structure and output findings for AI agent to generate project.md."""
    import json

    findings = {
        "project_type": project_type,
        "path": str(project_path),
        "files": [],
        "dirs": [],
        "config_files": {},
        "entry_points": [],
        "test_commands": [],
        "build_commands": [],
        "potential_metrics": [],
        "editable_hints": [],
        "dependencies": [],
        "tech_stack": [],
    }

    # Scan top-level files
    for f in sorted(project_path.iterdir()):
        if f.name.startswith(".") or f.name == "node_modules" or f.name == "__pycache__":
            continue
        if f.is_file():
            findings["files"].append(f.name)
            # Read key config files
            if f.name in ("package.json", "Cargo.toml", "go.mod", "pyproject.toml",
                          "requirements.txt", "Makefile", "CMakeLists.txt", "tsconfig.json",
                          "next.config.js", "next.config.mjs", "next.config.ts",
                          "vite.config.ts", "vite.config.js", "webpack.config.js",
                          "Dockerfile", "docker-compose.yml"):
                try:
                    content = f.read_text()[:3000]
                    findings["config_files"][f.name] = content
                except Exception:
                    pass
        elif f.is_dir():
            findings["dirs"].append(f.name)

    # Detect tech stack and entry points
    for fname, content in findings["config_files"].items():
        if fname == "package.json":
            try:
                pkg = json.loads(content)
                deps = {**pkg.get("dependencies", {}), **pkg.get("devDependencies", {})}
                findings["dependencies"] = list(deps.keys())[:20]
                scripts = pkg.get("scripts", {})
                if "dev" in scripts: findings["entry_points"].append(f"npm run dev ({scripts['dev']})")
                if "build" in scripts: findings["build_commands"].append(f"npm run build ({scripts['build']})")
                if "test" in scripts: findings["test_commands"].append(f"npm test ({scripts['test']})")
                if "start" in scripts: findings["entry_points"].append(f"npm start ({scripts['start']})")
                if "lint" in scripts: findings["test_commands"].append(f"npm run lint")
                # Detect frameworks
                if "next" in deps: findings["tech_stack"].append("Next.js")
                if "react" in deps: findings["tech_stack"].append("React")
                if "vue" in deps: findings["tech_stack"].append("Vue")
                if "express" in deps: findings["tech_stack"].append("Express")
                if "fastify" in deps: findings["tech_stack"].append("Fastify")
                if "@astrojs" in deps or "astro" in deps: findings["tech_stack"].append("Astro")
                if "vite" in deps: findings["tech_stack"].append("Vite")
                if "svelte" in deps: findings["tech_stack"].append("Svelte")
                if "tailwindcss" in deps: findings["tech_stack"].append("TailwindCSS")
                if "lighthouse" in deps: findings["potential_metrics"].append("Lighthouse score")
                if "vitest" in deps or "jest" in deps: findings["test_commands"].append("unit tests available")
            except json.JSONDecodeError:
                pass
        elif fname == "Cargo.toml":
            findings["tech_stack"].append("Rust")
            findings["build_commands"].append("cargo build --release")
            findings["test_commands"].append("cargo test")
            findings["potential_metrics"].append("binary size")
            findings["potential_metrics"].append("build time")
            findings["potential_metrics"].append("runtime performance")
        elif fname == "go.mod":
            findings["tech_stack"].append("Go")
            findings["build_commands"].append("go build")
            findings["test_commands"].append("go test ./...")
            findings["potential_metrics"].append("binary size")
        elif fname == "pyproject.toml":
            if "torch" in content: findings["tech_stack"].append("PyTorch")
            if "fastapi" in content: findings["tech_stack"].append("FastAPI")
            if "flask" in content: findings["tech_stack"].append("Flask")
            if "pytest" in content: findings["test_commands"].append("pytest")
        elif fname == "Makefile":
            for line in content.split("\n"):
                if line and not line.startswith("\t") and ":" in line and not line.startswith("."):
                    target = line.split(":")[0].strip()
                    if target not in (".PHONY", ".DEFAULT", "all"):
                        findings["entry_points"].append(f"make {target}")

    # Detect editable hints based on structure
    src_dirs = [d for d in findings["dirs"] if d in ("src", "lib", "pkg", "app", "cmd", "internal")]
    if src_dirs:
        findings["editable_hints"] = src_dirs
    else:
        findings["editable_hints"] = ["*.py", "*.js", "*.ts", "*.rs", "*.go"]

    # Format output for AI
    output = []
    output.append("=" * 60)
    output.append(f"PROJECT ANALYSIS: {project_path.name}")
    output.append("=" * 60)
    output.append(f"Type: {project_type}")
    output.append(f"Tech Stack: {', '.join(findings['tech_stack']) or 'unknown'}")
    output.append(f"Dependencies (top): {', '.join(findings['dependencies'][:10]) or 'none'}")
    output.append(f"\nDirectories: {', '.join(findings['dirs'][:15])}")
    output.append(f"Key Files: {', '.join(findings['files'][:15])}")
    output.append(f"\nBuild Commands:")
    for cmd in findings["build_commands"]:
        output.append(f"  - {cmd}")
    output.append(f"\nTest Commands:")
    for cmd in findings["test_commands"]:
        output.append(f"  - {cmd}")
    output.append(f"\nEntry Points:")
    for cmd in findings["entry_points"]:
        output.append(f"  - {cmd}")
    output.append(f"\nLikely Editable Areas:")
    for hint in findings["editable_hints"]:
        output.append(f"  - {hint}")
    output.append(f"\nSuggested Metrics:")
    for metric in findings["potential_metrics"]:
        output.append(f"  - {metric}")
    output.append("")
    output.append("Based on this analysis, generate a project.md that:")
    output.append("1. Defines a clear, measurable optimization goal")
    output.append("2. Specifies the experiment command and metric parsing")
    output.append("3. Identifies editable vs read-only files")
    output.append("4. Sets appropriate time budget and guard rails")
    output.append("5. Suggests 3-5 initial experiment ideas")
    output.append("")
    output.append("Write the project.md to autoresearch/project.md and present it to the user for review.")

    return "\n".join(output)


def main():
    parser = argparse.ArgumentParser(description="Initialize autoresearch in a project")
    parser.add_argument("path", nargs="?", default=".", help="Project directory (default: current)")
    parser.add_argument("--type", "-t", choices=list(TEMPLATES.keys()), default=None,
                        help="Project type (default: auto-detect)")
    parser.add_argument("--analyze-only", action="store_true",
                        help="Only analyze project and output findings (for AI agent to read)")
    args = parser.parse_args()

    project_path = Path(args.path).resolve()
    if not project_path.exists():
        print(f"❌ Path not found: {project_path}")
        sys.exit(1)

    # Auto-detect if not specified
    project_type = args.type or detect_project_type(str(project_path))
    template = TEMPLATES[project_type]

    # --analyze-only mode: output project analysis for AI to generate project.md
    if args.analyze_only:
        analysis = analyze_project(project_path, project_type)
        print(analysis)
        return

    # Create autoresearch directory
    ar_dir = project_path / "autoresearch"
    ar_dir.mkdir(exist_ok=True)
    (ar_dir / "experiments").mkdir(exist_ok=True)

    # Generate project.md
    time_budget = template["time_budget"]
    per_hour = max(1, int(3600 / time_budget))
    overnight = per_hour * 8

    direction = "lower" if template["metric_direction"] == "lower" else "higher"

    content = PROJECT_MD_TEMPLATE.format(
        goal=template["goal"],
        metric_name=template["metric_name"],
        direction=direction,
        command=template["command"],
        parse=template["parse"],
        editable=template["editable"],
        readonly=template["readonly"],
        time_budget=time_budget,
        guard=template["guard"],
        per_hour=per_hour,
        overnight=overnight,
    )

    md_path = ar_dir / "project.md"
    md_path.write_text(content)

    # Create results.tsv
    tsv_path = ar_dir / "results.tsv"
    if not tsv_path.exists():
        tsv_path.write_text("commit\tmetric\tmemory_mb\tstatus\tdescription\n")

    # Create .gitignore
    gitignore_path = ar_dir / ".gitignore"
    if not gitignore_path.exists():
        gitignore_path.write_text("experiments/\n")

    print(f"✅ Autoresearch initialized in {ar_dir}")
    print(f"📁 Type: {project_type}")
    print(f"🎯 Goal: {template['goal']}")
    print(f"📊 Metric: {template['metric_name']} ({template['metric_direction']} is better)")
    print(f"⏱️  Time budget: {time_budget}s per experiment (~{overnight} experiments/night)")
    print()
    print("Next steps:")
    print(f"  1. Edit {md_path} to customize your goal and metrics")
    print(f"  2. Start Claude Code/Codex in {project_path}")
    print(f'  3. Say: "Read autoresearch/project.md and start the experiment loop"')


if __name__ == "__main__":
    main()
